### ISSUE TITLE
Different country codes in cl-geo and FDP

### ISSUE THREAD

**Issue by marek-dudas** [openbudgets/pipeline-fragments#27]
FDP descriptor may contain a countryCode property with an ISO country code. Currently, the FDPtoRDF pipeline maps the value to the [cl-geo codelist](https://raw.githubusercontent.com/openbudgets/Code-lists/master/UnifiedViews/skosified/cl_geo/cl-geo.ttl) and uses it for obeu-dimension:organization. However, cl-geo does not use ISO country codes. So far, only Greece seems to be an issue (GR vs. EL) but there might be more differencies. @jindrichmynarz or anyone, any advice for a systematic solution for this?

Side question/note: the packager apparently might output more specific properties like cityCode. Those are not in the [FDP spec](http://specs.frictionlessdata.io/fiscal-data-package/#form-and-structure) and the pipeline ignores them currently.

**Comment by jindrichmynarz** [comment]
CL-GEO uses NUTS 0 codes for countries. They correspond to [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) codes except UK instead of GB for the United Kingdom and [EL instead of GR for Greece](https://en.wikipedia.org/wiki/NUTS_statistical_regions_of_Greece#Changes). A systematic solution can consist of creating a linkset between CL-GEO and [ISO 3166](http://id.loc.gov/vocabulary/countries.html). However, since there are only two exceptions, I think it's OK to hard-code them.

**Comment by marek-dudas** [comment]
Great, thank you. I hard-coded the exceptions and consider this solved.
