### ISSUE TITLE
FDP2RDF error: Dataset IRI not found in metadata

### ISSUE THREAD

**Issue by fathoni** [openbudgets/pipeline-fragments#31]
Hi @marek-dudas, we tried to transform this [data](https://next.openspending.org/viewer/848b8e447d0dfc798a77ef4f3a7bbcbd:bonn-simplified-2017?lang=en) to RDF using the hook in the packager. It seems that there is a problem with the FDP2RDF component.

Here is the message from the component:

> Component: FDP to RDF
> 
> Status: Failed
> 
> Start: 2017-08-04 16:56:38
> 
> End: 2017-08-04 16:56:38
> 
> Duration: 00:00:00
> 
> Cause: 
> Component execution failed.
> 
> Root cause: 
> LpException : Dataset IRI not found in metadata.
> 
> Messages:

The executed pipeline is available [here](https://next.openspending.org/viewer/848b8e447d0dfc798a77ef4f3a7bbcbd:bonn-simplified-2017?lang=en) (but requires you to have access to the FhG server).

Do we need to provide the dataset's IRI on the metadata? I could not find this field on the packager.

**Comment by marek-dudas** [comment]
Hi, I tried transforming the data locally and it worked fine. The error message is a little misleading, it can occur in various cases.

Anyway, the message should look like ```LpException : FdpToRdf-v0.8.0_1:Dataset IRI not found in metadata.```
I.e., there should be version info included in the error message. If it is not, it means somehow an older version of the FDPtoRDF component is running in the LinkedPipes again. I am not sure if @liyakun is available to check that. I can investigate more tomorrow.

**Comment by fathoni** [comment]
currently, @liyakun is on vacation so @hantongliu will try to check. Thanks @marek-dudas!

**Comment by marek-dudas** [comment]
I finally got to office and was able to look at it. There was indeed an old t-fdpToRdf.jar in /etl/deploy/jars inside the docker container. I don't know much about docker, so I just fixed it manually replacing the file inside the running container. The pipeline works fine now, but it is not a solution, since it will break at next restart of the image.

There is a wget command responsible for downloading up-to-date fdp .jar file in [linkedpipes dockerfile](https://github.com/openbudgets/integration/blob/master/docker-config/linkedpipes/Dockerfile) that seems fine, but it probably does not get executed. (Or maybe the commands from dockerfile are not executed at each image restart? Again, don't know much about docker.) It seems like if there was some data persistence in the container, because after each restart, there is a t-fdpToRdf.jar from May 31. Or at least that is the impression I get. (This same problem already happened once)

@hantongliu, hope you can help.

**Comment by pwalsh** [comment]
The only command that is executed when a docker image is run is [`CMD`](https://github.com/openbudgets/integration/blob/master/docker-config/linkedpipes/Dockerfile#L56). The rest is part of the build process, and has nothing to do with run time.

Replacing an asset (such as a jar) inside a running container is the absolute wrong way to deal with this - it just ensures that the old jar will be back when the container restarts.

The correct approach is to replace the image with a newer one, not to modify an existing image.

**Comment by marek-dudas** [comment]
@hantongliu, @liyakun, any update on rebuilding the LinkedPipes docker image?

**Comment by liyakun** [comment]
@marek-dudas We use the docker image from [gliderlabs/alpine:3.4](https://hub.docker.com/r/gliderlabs/alpine/), and then build LinkedPipes from there. There is no storage of docker image which contains the old version of [t-fdpToRdf.jar](https://github.com/opendatacz/lp-etl-components/raw/master/t-fdpToRdf/deploy/t-fdpToRdf.jar), so once we rebuild docker container with newest version of [t-fdpToRdf.jar](https://github.com/opendatacz/lp-etl-components/raw/master/t-fdpToRdf/deploy/t-fdpToRdf.jar), then it should be always in the docker image even if we restart the docker container, unless the docker container is rebuild with old version by wget.

Now the newest version of [t-fdpToRdf.jar](https://github.com/opendatacz/lp-etl-components/raw/master/t-fdpToRdf/deploy/t-fdpToRdf.jar) is already in the running docker container. Could you have a look? thanks.

**Comment by marek-dudas** [comment]
The pipeline is still working correctly, so I suppose we can close this. Thanks @liyakun .
